### ISSUE TITLE
invalid dependencies

### ISSUE THREAD

**Issue by delanym** [mservicetech/openapi-schema-validation#20]
This line is causing the project to depend on `:json-overlay:2.1.2-SNAPSHOT` which doesn't exist on Maven central 
https://github.com/mservicetech/openapi-schema-validation/blob/fdaa245b54b7dd921d6927f1fc19f63a7a79651f/pom.xml#L60

**Comment by delanym** [comment]
Although the json-overlay code exists, it depends on 
```
[INFO] com.networknt:json-overlay:jar:2.1.2-SNAPSHOT
[INFO] +- com.networknt:http-url:jar:2.1.2-SNAPSHOT:compile
[INFO] |  \- com.networknt:utility:jar:2.1.2-SNAPSHOT:compile
```

http-url is not available at https://github.com/networknt

**Comment by stevehu** [comment]
All the dependencies exist in the snapshot repo. We will release a new version soon and will revise the dependencies. Meanwhile, you can add the sonatype snapshot repo to your maven project.
