### ISSUE TITLE
CVEs reported in Maven central - Update dependencies for removal

### ISSUE THREAD

**Issue by vishwesh-D-kumar** [mservicetech/openapi-schema-validation#22]
https://mvnrepository.com/artifact/com.mservicetech/openapi-schema-validation/2.0.5 lists 8 CVE security issues, which is a lot of security consideraitions . At a glance these can be removed by updating dependent libraries,  (such as fasterXML jackson-databind version to 2.140-rc1 or above). A quick minor release for this would allow teams to easily uptake this great library, without having to go through a lot of security considerations.

**Comment by vishwesh-D-kumar** [comment]
@stevehu @GavinChenYan kindly have a look . Thanks!

**Comment by vishwesh-D-kumar** [comment]
Sounds good , I think the updates to snakeyaml and jackson should do the trick

**Comment by vishwesh-D-kumar** [comment]
How long would this take to appear in maven central?

**Comment by stevehu** [comment]
We need a little bit more tests and should have a release this weekend. Thanks.

**Comment by vishwesh-D-kumar** [comment]
@stevehu   @GavinChenYan could you kindly confirm on the new release coming this weekend ? We wanted some confirmation to plan accordingly. Thanks!
