### ISSUE TITLE
CVE issues fixes;  MAVEN

### ISSUE THREAD

**Issue by mayank18049** [mservicetech/openapi-schema-validation#24]
We wanted to use this library for our development needs. Are there any functional problems after upgrading CVE causing dependencies? If so, could we expect a release with updated dependency down the line.

**Comment by mayank18049** [comment]
@stevehu @GavinChenYan, Can you give an update on this

**Comment by GavinChenYan** [comment]
Released new version: 2.0.6

**Comment by GavinChenYan** [comment]
@mayank18049  released new release with  updated dependency

**Comment by mayank18049** [comment]
Thanks for the quick response!  @GavinChenYan
