### ISSUE TITLE
MEMORY LEAK ISSUE

### ISSUE THREAD

**Issue by vijayseid** [mservicetech/openapi-schema-validation#25]
Hi team, facing an memory leak issue, memory keep on increasing & reaches the max heap. 

Test Scenario:

JMETER : 1000 threads, duration 72000.

**Comment by GavinChenYan** [comment]
@vijayseid  Do you have detail test case? And the error message detail?
We will take a look

**Comment by GavinChenYan** [comment]
@vijayseid  Please take a look you code, for temp solution, please verify two things:
1, OpenApiValidator openApiValidator = new OpenApiValidator(),  
this should be defined at instance level, don;t new it for every request

2. RequestEntity requestEntity = new RequestEntity(); 
   please set it for null after validation

We will take a look library and try to have enhancement

**Comment by vijayseid** [comment]
Thanks for the suggestion @GavinChenYan. Doing the same, OpenApiValidator instance is created on application level.

**Test Scenarios:** 
Test Load : 1000 User threads, 30 Ramp up seconds, Durations 24hours, loop count  : Infinite. 
Test Tool : Jmeter
No of HTTP Request : 1
<img width="422" alt="image" src="https://github.com/mservicetech/openapi-schema-validation/assets/61611758/6ca1ded6-54be-4859-a74f-2f70ed83dd04">

**NOTE:** 

- Using Spring Boot application with JAVA 17, and limit the heap memory to 2GB.
- My spring application has only one function, & that is the openapi schema validation. NO OTHER CODE BLOCKS PRESENT.
- Using JConsole to monitor the heap memory

When I Start the test, Heap memory graphs seems to up & down only, but the **OLD GEN** Graph slowly claims up & not comes down. So Slowly my heap memory gets increasing & reached the max with in 24hours. Facing an **Exception in thread "main" java.lang.OutOfMemoryError: Java heap space issue** on my spring boot application.

<img width="826" alt="image" src="https://github.com/mservicetech/openapi-schema-validation/assets/61611758/1b91db26-f270-45b0-92a0-a3a238d43151">

please take a loot at this graph, old gen keep on increasing.

For confirming this is to be a memory leak issue, tried the same type of load to another lib (SwaggerValidatior/ OpenApiInteractionValidator), there Clearly I can see the Heap & Old Gen heap goes up & comes down after sometime. You can see that graph as well here

<img width="695" alt="image" src="https://github.com/mservicetech/openapi-schema-validation/assets/61611758/9c559de9-f754-445c-b4c3-b2c4c9c5608a">

**So it's clearly says some memory leak on this lib.**

Few tries to identify the memory leak issue,
**Request Entity**  & **Status** Objects are set to null after validation

If anything require from my side, please let me know & will try to submit here.

Your Suggestion @GavinChenYan  & Fix help me to solve my issue & I will be ready for Production  **˶ᵔ ᵕ ᵔ˶**

Thanks for the support.

**Comment by vijayseid** [comment]
Last Night run the perf testing again, here the screenshot of that @GavinChenYan 

Heap Memory :

![image](https://github.com/mservicetech/openapi-schema-validation/assets/61611758/1582d9ca-3fcd-4d48-ac7e-2786211d2535)


Old Gen :

![image](https://github.com/mservicetech/openapi-schema-validation/assets/61611758/3e4b204a-e3ec-467c-a757-dd5028ef3d69)


Jmeter Result : 
![image](https://github.com/mservicetech/openapi-schema-validation/assets/61611758/ab24a4e5-edc1-43fe-8072-12ff86a08d7e)

**Comment by vijayseid** [comment]
Heap memory reaches max & application failed after 16hour of testing

![image](https://github.com/mservicetech/openapi-schema-validation/assets/61611758/6ca0172d-b2a2-45f7-865b-b6e919eb67c9)

Old Gen: 

![image](https://github.com/mservicetech/openapi-schema-validation/assets/61611758/8bdea904-8917-4a65-97cb-539214855fde)

**Comment by vijayseid** [comment]
@GavinChenYan 

22/05 result :

![image](https://github.com/mservicetech/openapi-schema-validation/assets/61611758/aef39533-e521-4dcd-a858-e72b803d29e1)


![image](https://github.com/mservicetech/openapi-schema-validation/assets/61611758/5fce84c4-0d33-41d5-82a7-1ee5875177eb)


![image](https://github.com/mservicetech/openapi-schema-validation/assets/61611758/1e74f9ca-ff19-4c11-af8f-81f876dc8a5b)


![image](https://github.com/mservicetech/openapi-schema-validation/assets/61611758/8636041d-3a34-4a4c-931b-91906fe51f96)

**Comment by GavinChenYan** [comment]
@vijayseid Will try to have a new release for this issue. Sorry for the delay

**Comment by vijayseid** [comment]
@GavinChenYan thanks for supporting

Using this constructor

    public OpenApiValidator(InputStream openapi) {
        spec = new BufferedReader(new InputStreamReader(openapi, StandardCharsets.UTF_8)).lines().collect(Collectors.joining("\n"));
        openApiHelper = new OpenApiHelperCustom(spec);
        schemaValidator = new SchemaValidator(openApiHelper.openApi3);
    }

**Comment by GavinChenYan** [comment]
@vijayseid 

I had some test on my side.  

And I think it could be inputstream close issue which cause the memory problem.

Basically. as long as you properly handle and close the input stream, there should not be a memory leak problem in this specific code snippet.

However, it's important to ensure that the input stream is closed correctly, especially if this code is executed multiple times or if there are other parts of your application that may not release resources properly. If the input stream is not closed in some other part of your code, it could potentially lead to memory leaks.

I created a PR for closing inputstream:
https://github.com/mservicetech/openapi-schema-validation/pull/26

I am going to have a new release today.

But for your case, you are using inputstream which initialled by yourself which shouldn't be controlled by library. Can you please make sure you close the inputsteam by yourself ?

Thanks,

Gavin

**Comment by vijayseid** [comment]
One thing to add here, I have modified the the OpenApiValidator class & used the modified class as well. In modified OpenApiValidator class, 

    public OpenApiValidatorCustom(String openapiPath) {
        //InputStream in = this.getClass().getClassLoader().getResourceAsStream(openapiPath);
        spec =openapiPath;
        		//new BufferedReader(new InputStreamReader(in, StandardCharsets.UTF_8)).lines().collect(Collectors.joining("\n"));
        openApiHelper = new OpenApiHelperCustom(spec);
        schemaValidator = new SchemaValidator(openApiHelper.openApi3);
    }


Instead of passing the openapipath, I'm passing the openapi spec & directly assigned to spec. This try also giving the memory leak. 

NOTE: I don't have any OpenApiHelper dependency previously, after adding that dependency, memory leaks is too better.
Is that memory leak because of missing dependency.


I closed the inputstream as well, but that didn't help me. But OpenApiHelper dependency helps me to reduce 90% of memory, yeah I can say there is no leat at all, but have to verify again.


Also lowered the dependency versions & you can see the results here,

		
		<dependency>
			<groupId>org.openapi4j</groupId>
			<artifactId>openapi-parser</artifactId>
			<version>1.0.5</version>
		</dependency>
		<dependency>
			<groupId>com.networknt</groupId>
			<artifactId>openapi-helper</artifactId>
			<version>2.0.32</version>
		</dependency>
		
		<dependency>
			<groupId>com.networknt</groupId>
			<artifactId>json-overlay</artifactId>
			<version>2.1.2</version>
		</dependency>
		
		<dependency>
			<groupId>com.networknt</groupId>
			<artifactId>openapi-parser</artifactId>
			<version>2.1.2</version>
		</dependency>



![image](https://github.com/mservicetech/openapi-schema-validation/assets/61611758/7a78dbce-97ae-4ba2-b5df-ce1c6cdebc95)


![image](https://github.com/mservicetech/openapi-schema-validation/assets/61611758/686f9e07-77ed-40f1-a12d-3cf32761ef48)


Have to figure out, which helps me to fix this.

**Comment by GavinChenYan** [comment]
@vijayseid 
if you are using 

OpenApiValidatorCustom(String openapiPath)

It may cause memory issue since the inputstream close issue. We have changed the code with try/catch resource block to close the inputstream. 

For the dependency, I don't think it will cause the memory leak issue. But we will add it to the pom file as well


	<dependency>
		<groupId>com.networknt</groupId>
		<artifactId>openapi-helper</artifactId>
		<version>2.0.32</version>
	</dependency>

**Comment by vijayseid** [comment]
@GavinChenYan OpenApiValidatorCustom(String openapiPath)
With this I’m not using an inputstream… 
Directly passing the spec & assigned it to spec
Like this, I’m sure after the dep only it resolves my memory leak issue. Will confirm it with again today or tomorrow.


public OpenApiValidatorCustom(String openapiPath) {
    spec =openapiPath;
    openApiHelper = new OpenApiHelperCustom(spec);
    schemaValidator = new SchemaValidator(openApiHelper.openApi3);
}

**Comment by GavinChenYan** [comment]
@vijayseid Thanks for the confirmation. Please let us know the result. And we will release new version soon.

**Comment by vijayseid** [comment]
@GavinChenYan 

![image](https://github.com/mservicetech/openapi-schema-validation/assets/61611758/8812c491-8604-40c6-90a6-a81006057cb0)

![image](https://github.com/mservicetech/openapi-schema-validation/assets/61611758/cbd23898-7c65-4d19-9fc1-94b3cfde44a8)

TPS : 123.5/sec, earlier around 75-89/sec. Improved after closing the inputstream, Memory graph also seems to fine. Will plan to run for 48hrs perf test. 

Will share those results after the test completes.



Thanks.
