### ISSUE TITLE
Fix Request Body Validation Bug

### ISSUE THREAD

**Issue by vijayseid** [mservicetech/openapi-schema-validation#27]
Hi @GavinChenYan  @stevehu 
Find a Bug on validating the Request body, could you please fix it.

OpenApiSpec has Mandatory field on request body, here is the piece of line added

RequestBody:
      required:
        **- feature**
      type: object
      properties:
        billerDivisionId:
          type: string
          description: Division Id for account, same as spc division id
        billerAccountNumber:
          type: string
          description: Account number in a billing system
        soloAccountId:
          type: string
          description: Account Id in SOLO
        feature:
          type: string
          description: 'Use case for which this token needs to be generated (example: enable-paperless-billing)'
      description: Billing details

### **Scenario 0** : Positive - Works as expected

![image](https://github.com/mservicetech/openapi-schema-validation/assets/61611758/bef5f015-3661-4fdd-8413-2f7b700a49b4)

### **Scenario 1** :  Negative - Works as expected

If I Skip the field **feature**, I got the perfect validation says this field is required & it's missed.

![image](https://github.com/mservicetech/openapi-schema-validation/assets/61611758/bbf1af69-d7ef-4406-a6c4-06cee3aa5d71)

### **Scenario 2** :  Negative - Failed to pass

If I Skip the entire Request body(not passing any body), I Didn't get any validation error, & validation was successful. It should throw the same as scenario 1.

![image](https://github.com/mservicetech/openapi-schema-validation/assets/61611758/aacca7d0-930f-41b1-a2c2-f92b29a1a228)

**Comment by GavinChenYan** [comment]
@vijayseid Thanks, will take a look this issue

**Comment by GavinChenYan** [comment]
@vijayseid  For your case, you put body type as null, which normally will not happen on API call. If we specify the json format on postman, it will have error  as expected:
![image](https://github.com/mservicetech/openapi-schema-validation/assets/25724405/06e39bc0-be7c-48d8-993d-99990e33c8cd)

But for your case, I add a fix as well.  And added two test cases for reference. Please take a look PR:
https://github.com/mservicetech/openapi-schema-validation/pull/28

**Comment by vijayseid** [comment]
@GavinChenYan Thanks for the quick fix, great advantage of using this lib is **lightening response & fix from developer** .

**Comment by vijayseid** [comment]
@GavinChenYan @stevehu 

Even though if  pass the request body as empty or null, still it's not validating properly, I saw the change & made the same change on custom lib as well.

Passing as EMPTY :

![image](https://github.com/mservicetech/openapi-schema-validation/assets/61611758/102551c4-7732-42b0-baa7-873f33f312ee)


Passing as NULL:

![image](https://github.com/mservicetech/openapi-schema-validation/assets/61611758/253ad80e-b65d-43bf-a501-cc8b08d522c6)


Can you please confirm you fix?

**Comment by vijayseid** [comment]
@GavinChenYan Confirmed, content type is application/json & my request body is null.
Still it is not throwing the error for me

requestEntity.setContentType(MediaType.APPLICATION_JSON_VALUE);

![image](https://github.com/mservicetech/openapi-schema-validation/assets/61611758/816870a1-b9ce-42e8-b6f4-6e4e7e124533)


![image](https://github.com/mservicetech/openapi-schema-validation/assets/61611758/942ba2a4-983b-4fe8-bf55-a890bf1bb2bc)
