### ISSUE TITLE
fix #27 is not working

### ISSUE THREAD

**Issue by vijayseid** [mservicetech/openapi-schema-validation#29]
@GavinChenYan @stevehu 

Even though if  pass the request body as empty or null, still it's not validating properly, I saw the change & made the same change on custom lib as well.

Passing as EMPTY :

![image](https://github.com/mservicetech/openapi-schema-validation/assets/61611758/102551c4-7732-42b0-baa7-873f33f312ee)

Passing as NULL:

![image](https://github.com/mservicetech/openapi-schema-validation/assets/61611758/253ad80e-b65d-43bf-a501-cc8b08d522c6)

Can you please confirm you fix?

_Originally posted by @vijayseid in https://github.com/mservicetech/openapi-schema-validation/issues/27#issuecomment-1587034064_

**Comment by vijayseid** [comment]
@GavinChenYan  
Test case : testRequestBodyEmpty()

if you pass request body as "" empty, it should throw as required fields right which we missed, but it says  **No request body is expected for %s on path %s.":"ERROR"**.   But our case need an request body with required field.



Test Case : testRequestBodyNull()

I have tested by passing null, but it passed without any error

![image](https://github.com/mservicetech/openapi-schema-validation/assets/61611758/f7fe6175-3ab2-4d12-8171-238d04409c60)

**Comment by GavinChenYan** [comment]
@vijayseid Sorry for the delay. 
I will take a look the status code for the error. 

For second senario, can you take a look your code implementation?  Do you set the request body ?
requestEntity.setRequestBody(req);

**Comment by vijayseid** [comment]
Yeah @GavinChenYan I'm setting the request body

schemaValidateRequest.setRequestBody(requestBody);

**Comment by GavinChenYan** [comment]
That's weird, my case works fine

**Comment by GavinChenYan** [comment]
@vijayseid there is logic in the code:
            if ((requestEntity.getContentType()==null || requestEntity.getContentType().startsWith("application/json"))) {

what content type you are using? can you debug to find it? only in case it is null or application/json , it trigger body validation

**Comment by vijayseid** [comment]
@GavinChenYan  Confirmed, content type is application/json & my request body is null.
Still it is not throwing the error for me

**requestEntity.setContentType(MediaType.APPLICATION_JSON_VALUE);**

**Request body is null - >**

![image](https://github.com/mservicetech/openapi-schema-validation/assets/61611758/816870a1-b9ce-42e8-b6f4-6e4e7e124533)

**Status is null ->**

![image](https://github.com/mservicetech/openapi-schema-validation/assets/61611758/942ba2a4-983b-4fe8-bf55-a890bf1bb2bc)


if I pass the body, it will say expected key is required & it is missing

**Comment by vijayseid** [comment]
Also @GavinChenYan  when new release will happen? any approx
 date?

**Comment by GavinChenYan** [comment]
version 2.0.8 released:

Uploaded to ossrh: https://oss.sonatype.org:443/service/local/staging/deployByRepositoryId/commservicetech-1013/com/mservicetech/openapi-schema-validation/2.0.8/openapi-schema-validation-2.0.8.jar.asc.asc (673 B at 7.9 kB/s)
