### ISSUE TITLE
Error Message doesn't say the type of filed (QUERY/HEADER/PATH)

### ISSUE THREAD

**Issue by vijayseid** [mservicetech/openapi-schema-validation#31]
@GavinChenYan @stevehu 

Error message doesn't say required field is QUERY or HEADER or PATH Parameter. 

For this modified the code, can you please review my changes & approve it?

Here is the pull request - >   https://github.com/mservicetech/openapi-schema-validation/pull/30

**Comment by GavinChenYan** [comment]
approved and merged. Thanks
