### ISSUE TITLE
HTTP method is case sensitive (regression)

### ISSUE THREAD

**Issue by david0** [mservicetech/openapi-schema-validation#44]
In 2.0.8 both `GET` and `get` was working.

In 2.0.9 only the lowercase version works, which is a little unhandy since `HttpServletRequest.getMethod()` returns it in uppercase.

This is regression caused by this commit: 7bb4983a2d0f8e9b5687a843d6ad6619284e929a

**Comment by stevehu** [comment]
@daglem, I think we should support both cases to maintain backward compatibility. Would you be able to do that? Thanks.
